# Generated by Django 5.2 on 2025-04-28 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^.{4,}$')], verbose_name='Товар'),
        ),
    ]
